parameters:
    form.handler.class: EldoMagan\FormHandlerBundle\Service\FormHandler
    form.handler.argument_resolver.class: EldoMagan\FormHandlerBundle\ArgumentResolver\FormHandlerValueResolver

services:
    form.handler:
        class: %form.handler.class%
        arguments:
            - "@form.factory"
            - "@request_stack"

    form.handler.argument_resolver:
        class: %form.handler.argument_resolver.class%
        arguments: ["@service_container"]
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }